################################################################################
############################ Variables to change ###############################
##### Sources directory
SRC_DIR		  = src
RES_DIR     = res
THEME_DIR   = theme
BIB_DIR     = bibliography

##### Main file, without .tex extension.
NAME		    = memoire

##### Output directory
# If not modified, it is the directory which holds the MakeFile
OUTPUT_DIR	= _build

##### Executable/output to use: PDFLATEX, DVILUATEX
CC			    = $(PDFLATEX)
CC_BIB		  = $(BIBTEX)
USE_BIB		  = false
################################################################################
